var mongoose = require('mongoose');
var Character = new mongoose.Schema({
    name: String,
    player: String,
    class: String,
    level: {type: Number, default: 0},
    race: String,
    alignment: String,
    deity: String,
    size: String,
    age: {type: Number, default: 18},
    gender: String,
    height: String,
    weight: {type: Number, default: 180},
    eyes: String,
    hair: String,
    skin: String,
    str: {type: Number, default: 0},
    dex: {type: Number, default: 0},
    con: {type: Number, default: 0},
    int: {type: Number, default: 0},
    wis: {type: Number, default: 0},
    cha: {type: Number, default: 0},
    hp: {type: Number, default: 0},
    ac: {type: Number, default: 0},
    speed: {type: Number, default: 0},
    initiative: {type: Number, default: 0},
    fortitude_base: {type: Number, default: 0},
    reflex_base: {type: Number, default: 0},
    will_base: {type: Number, default: 0},
    bab: {type: Number, default: 0},
});
mongoose.model('mongoDBCreative', Character);